name: CI/CD → Azure Container Instances
on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:

jobs:
  pipeline:
    uses: mewfeuille115/org-templates/.github/workflows/acr-staged-build-push.yaml@main
    with:
      image-name: ec-maven-users-api
      image-tag: latest
      dockerfile-path: Dockerfile
    secrets:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
